name: Create Sample File

on:
  push:
    branches:
      - main

jobs:
  create_file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Sample File
      run: |
        echo "This is a sample file created by GitHub Actions" > sample.txt
        git config user.name "GitHub Actions"
        git config user.email "actions@example.com"
        git add sample.txt
        git commit -m "Add sample.txt via GitHub Actions"
        git push origin main
