name: CI/CD Pipeline

on:
  push:
    branches:
      - main

stages:
  - build
  - test
  - deploy

jobs:
  build-my-first-job:
    stage: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "This is the first build job."

  test-my-first-job:
    stage: test
    runs-on: ubuntu-latest
    needs: build-my-first-job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test
        run: echo "This is the first test job."

  deploy-first-job:
    stage: deploy
    runs-on: ubuntu-latest
    needs: test-my-first-job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "This is the deploy first job."
