name: Deploy to WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to WordPress
      run: |
        cd ubuntu/wordpress/project
        zip -r wordpress.zip .

        # Assuming you have SSH keys set up on your server
        scp -o StrictHostKeyChecking=no -r wordpress.zip user@your-server-ip:/path/to/destination

        # Connect to the server and unzip the WordPress files
        ssh -o StrictHostKeyChecking=no user@your-server-ip 'cd /path/to/destination && unzip -o wordpress.zip'

        # Clean up the zip file
        rm wordpress.zip
